### ISSUE TITLE
Copy Icon Not Functioning Properly

### ISSUE THREAD

**Issue by yo-harsh** [zenml-io/zenml-dashboard#539]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General
Issue Overview:

The copy icon functionality is not working as expected, preventing users from copying content.
in pipelines when we check Dag Visualizers - Details there the copy icon doesn't work

**Comment by Cahllagerfeld** [comment]
Hello @yo-harsh,

I remember a conversation in our Slack with @schustmi about this. Did you work on this already? 
I want to give you a short heads up, that this issue was initially created for the now "old" dashboard.
Depending on the copy-button it should either be fixed in the new dashboard, or is about to come very soon.

Let me know if you have any questions 👍

**Comment by yo-harsh** [comment]
hello, i think this issue is resolved the last time i had checked the dashboard it was working.. though you can recheck.On May 6, 2024 2:55 PM, Cahllagerfeld ***@***.***> wrote:
Hello @yo-harsh,
I remember a conversation in our Slack with @schustmi about this. Did you work on this already?
I want to give you a short heads up, that this issue was initially created for the now "old" dashboard.
Depending on the copy-button it should either be fixed in the new dashboard, or is about to come very soon.
Let me know if you have any questions 👍

**Comment by Cahllagerfeld** [comment]
Okay, I'll close this issue then 👍
