### ISSUE TITLE
Pipeline run not getting tracked.

### ISSUE THREAD

**Issue by debanshu08** [zenml-io/zenml-dashboard#60]
I ran a sample code with two steps in my local using the default stack 
On doing zenml pipeline list I can see the pipeline but from zenml up I can't 
Is there something which is messing or some mapping is not being done in the dashboard?

Does the command - zenml up --blocking -> Doesn't track the pipeline runs in Windows? Directly running zenml up throws this error
Running the ZenML server locally as a background process is not supported on Windows. Please use the `--blocking` flag to run the server in blocking mode, or run the server in a Docker container by setting `--docker` instead.

**Comment by AntoineDps** [comment]
I have the same error, tried with `zenml login --local --blocking` but obtained the following error:

ModuleNotFoundError: No module named 'jwt' During handling of the above exception, another exception occurred: RuntimeError: The local daemon ZenML server provider is unavailable because the ZenML server requirements seems to be unavailable on your machine. This is probably because ZenML was installed without the optional ZenML Server dependencies. To install the missing dependencies run pip install "zenml[server]==0.75.0".

The error remains after installing `pip install "zenml[server]==0.75.0"`

**Comment by htahir1** [comment]
@AntoineDps maybe its to do with virtualenvs and paths in your machine? try uninstall zenml `pip uninstall zenml` and create a fresh virtualenv and try again

**Comment by AntoineDps** [comment]
Thank you for the answer @htahir1 !

It worked with a new environment! I have tried again with my old environment... and it works now, for some reasons..

Thanks again!
